import dynamic from "next/dynamic";
import Head from "next/head";
import { useState } from "react";

const DynamicShape = dynamic(() => import("../components/Shape"), {
  ssr: false,
});

export default function Home() {
  const [color, setColor] = useState();
  const onClickHandler = (color) => {
    setColor(color)
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          width: 1000,
          height: 500,
          background: "url(/contact.jpg)",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      >
        <DynamicShape color={color} setColor={setColor}/>
      </div>
      <div className="btn-container">
        <button onClick={() => onClickHandler("red")} className="btn">
          <span style={{ color: "red" }}>🁢</span> Label 1
        </button>
        <button onClick={() => onClickHandler("blue")} className="btn">
          <span style={{ color: "blue" }}>🁢</span> Label 2
        </button>
        <button onClick={() => onClickHandler("green")} className="btn">
          <span style={{ color: "green" }}>🁢</span> Label 3
        </button>
      </div>
    </div>
  );
}
